export type BlogPost = {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  image: string;
  readTime: string;
};

export const blogPosts: BlogPost[] = [
  // AI & Automation
  {
    id: '1',
    title: "How AI Chatbots Can Cut Customer Support Costs by 50%",
    excerpt: "Learn how modern AI chatbots resolve issues instantly, saving your team time and keeping customers happy 24/7.",
    date: "2025-05-10",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
  {
    id: '2',
    title: "Automating Your Sales Process with AI Voice Agents",
    excerpt: "Discover how AI calling agents can qualify leads and book appointments automatically, scaling your sales team overnight.",
    date: "2025-05-08",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },
  {
    id: '3',
    title: "AI in Recruitment: Hiring the Best Talent Faster",
    excerpt: "How automated video interviews and behavioral analysis are helping companies hire top talent in a fraction of the time.",
    date: "2025-05-05",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=800&auto=format&fit=crop",
    readTime: "5 min read",
  },
  {
    id: '4',
    title: "Will AI Replace Software Developers in 2025?",
    excerpt: "The short answer is no. Read why AI is a tool to help developers build software faster, rather than a replacement.",
    date: "2025-05-01",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  },
  {
    id: '5',
    title: "Understanding Machine Learning for Non-Technical Founders",
    excerpt: "A simple, jargon-free guide to how machine learning works and how it can increase your business revenue.",
    date: "2025-04-28",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1507146426996-ef05306b995a?q=80&w=800&auto=format&fit=crop",
    readTime: "9 min read",
  },
  {
    id: '6',
    title: "The ROI of Integrating AI into Your Legacy Systems",
    excerpt: "Upgrading old software with AI features doesn't have to be expensive. Here is how to measure the return on investment.",
    date: "2025-04-25",
    category: "Artificial Intelligence",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },

  // Web Development
  {
    id: '7',
    title: "Why Your Business Needs a Custom Web App in 2025",
    excerpt: "Off-the-shelf software only goes so far. Find out when it makes financial sense to build a custom application.",
    date: "2025-04-20",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  },
  {
    id: '8',
    title: "Next.js vs. React: Which Framework is Best for You?",
    excerpt: "A simple breakdown of the differences between React and Next.js, and which one you should choose for your next project.",
    date: "2025-04-18",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },
  {
    id: '9',
    title: "5 Signs Your E-commerce Website Needs a Redesign",
    excerpt: "If your online store is suffering from slow load times or high cart abandonment, it might be time for an upgrade.",
    date: "2025-04-15",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=800&auto=format&fit=crop",
    readTime: "5 min read",
  },
  {
    id: '10',
    title: "How Website Speed Impacts Your Google Rankings",
    excerpt: "Google prioritizes fast websites. Learn how we optimize web apps to load in under a second.",
    date: "2025-04-12",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
  {
    id: '11',
    title: "Progressive Web Apps (PWAs) Explained",
    excerpt: "What is a PWA, and why might it be a cheaper alternative to building a native iOS or Android app?",
    date: "2025-04-10",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  },
  {
    id: '12',
    title: "The Importance of Mobile-First Design",
    excerpt: "With over 60% of internet traffic coming from phones, designing for mobile isn't just an option—it's mandatory.",
    date: "2025-04-05",
    category: "Web Development",
    image: "https://images.unsplash.com/photo-1522199755839-a2bacb67c546?q=80&w=800&auto=format&fit=crop",
    readTime: "5 min read",
  },

  // Business Growth
  {
    id: '13',
    title: "How to Choose the Right IT Agency for Your Startup",
    excerpt: "Don't waste your budget on the wrong tech partner. Here are 5 questions you must ask before hiring a development team.",
    date: "2025-04-01",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },
  {
    id: '14',
    title: "Understanding API Integrations: A Guide for Founders",
    excerpt: "APIs connect your software together. Here is a simple explanation of how they work and why your business needs them.",
    date: "2025-03-28",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
  {
    id: '15',
    title: "Digital Transformation: Where Do You Start?",
    excerpt: "Moving your business from paper and spreadsheets to modern software can be scary. We break down the first steps.",
    date: "2025-03-25",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop",
    readTime: "9 min read",
  },
  {
    id: '16',
    title: "The Hidden Costs of Bad UX Design",
    excerpt: "If your software is confusing to use, you are losing money. Learn how user experience directly impacts your revenue.",
    date: "2025-03-20",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  },
  {
    id: '17',
    title: "MVP Development: Launching Your Idea Faster",
    excerpt: "Don't build every feature at once. Learn how a Minimum Viable Product can help you test your idea in the market cheaply.",
    date: "2025-03-15",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
  {
    id: '18',
    title: "Why SEO is Critical for B2B Software Companies",
    excerpt: "If your ideal clients can't find you on Google, you don't exist. Our complete guide to SEO for tech businesses.",
    date: "2025-03-10",
    category: "Business Growth",
    image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?q=80&w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },

  // Cloud & Security
  {
    id: '19',
    title: "The Ultimate Guide to Securing Your Cloud Infrastructure",
    excerpt: "Protect your customer data with these essential security protocols for AWS, Azure, and Google Cloud.",
    date: "2025-03-05",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=800&auto=format&fit=crop",
    readTime: "10 min read",
  },
  {
    id: '20',
    title: "What is Zero Trust Architecture? (Simply Explained)",
    excerpt: "Never trust, always verify. Discover why the biggest companies are shifting to Zero Trust security models.",
    date: "2025-03-01",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1510511459019-5efa3274cb15?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  },
  {
    id: '21',
    title: "Migrating from On-Premise to the Cloud",
    excerpt: "A step-by-step guide to safely moving your business servers to the cloud without losing data or experiencing downtime.",
    date: "2025-02-25",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop",
    readTime: "9 min read",
  },
  {
    id: '22',
    title: "Why Regular Security Audits Are Non-Negotiable",
    excerpt: "Hackers move fast. Learn why testing your own software for vulnerabilities is the best defense against data breaches.",
    date: "2025-02-20",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=800&auto=format&fit=crop",
    readTime: "6 min read",
  },
  {
    id: '23',
    title: "Serverless Architecture: The Future of Web Hosting",
    excerpt: "Find out how going 'serverless' can actually lower your hosting bills and automatically scale during traffic spikes.",
    date: "2025-02-15",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1620288627228-568eb4bd92db?q=80&w=800&auto=format&fit=crop",
    readTime: "8 min read",
  },
  {
    id: '24',
    title: "How to Ensure Your Web App is HIPAA Compliant",
    excerpt: "Building software for healthcare? Here are the exact security standards you must follow to protect patient data.",
    date: "2025-02-10",
    category: "Cloud & Security",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop",
    readTime: "7 min read",
  }
];
