import { Metadata } from 'next';
import React from 'react';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import ROICalculator from '@/components/shared/ROICalculator';
import { Calculator, ArrowRight, CheckCircle2 } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI Automation ROI Calculator | Free Mathematical Model | Vidhyonix',
  description: 'Calculate your projected operational cost savings, ticket deflection rates, and recovered manual hours with our interactive AI automation ROI calculator.',
  alternates: {
    canonical: 'https://vidhyonix.com/free-tools/ai-automation-roi-calculator',
  }
};

export default function AIAutomationROIPage() {
  return (
    <>
      <main className="relative min-h-screen bg-brand-dark overflow-hidden text-white">
        <Header />

        {/* Hero Section */}
        <section className="relative pt-40 pb-16 border-b border-white/5 overflow-hidden">
          <div className="container mx-auto px-4 max-w-4xl text-center space-y-4">
            <span className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-white/5 border border-white/10 text-xs font-mono text-brand-cyan uppercase tracking-wider">
              <Calculator size={13} /> Interactive Financial Model
            </span>
            <h1 className="text-3xl sm:text-4xl md:text-5xl font-heading font-extrabold text-white tracking-tight">
              AI Automation ROI Calculator
            </h1>
            <p className="text-base md:text-lg text-slate-300 max-w-2xl mx-auto">
              Model real-world cost recoveries across customer support ticket deflection, internal administrative hours, and operational headcount avoidance.
            </p>
          </div>
        </section>

        {/* Calculator Container */}
        <section className="py-16">
          <div className="container mx-auto px-4 max-w-4xl">
            <ROICalculator />
          </div>
        </section>

        {/* Supporting Explanation */}
        <section className="py-20 bg-white/5 border-t border-white/5">
          <div className="container mx-auto px-4 max-w-4xl space-y-6">
            <h2 className="text-2xl font-heading font-bold text-white text-center">
              How the Mathematical Model Works
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-xs text-slate-300">
              <div className="p-6 rounded-2xl bg-brand-dark/90 border border-white/5 space-y-2">
                <h3 className="font-bold text-white text-sm">Customer Support Deflection</h3>
                <p className="leading-relaxed text-slate-400">
                  Calculates tier-1 support ticket resolution using a benchmark 60% autonomous deflection rate, multiplied by your average cost per resolution.
                </p>
              </div>
              <div className="p-6 rounded-2xl bg-brand-dark/90 border border-white/5 space-y-2">
                <h3 className="font-bold text-white text-sm">Workflow Hours Recovered</h3>
                <p className="leading-relaxed text-slate-400">
                  Measures repetitive manual processes (invoice entry, data re-keying, email triage) using an 80% automated execution reduction factor.
                </p>
              </div>
              <div className="p-6 rounded-2xl bg-brand-dark/90 border border-white/5 space-y-2">
                <h3 className="font-bold text-white text-sm">Headcount Avoidance</h3>
                <p className="leading-relaxed text-slate-400">
                  Projects the savings generated by handling double transaction volume without needing to linearly hire additional operational personnel.
                </p>
              </div>
            </div>
          </div>
        </section>

        <Footer />
      </main>
    </>
  );
}
